//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_SONOLIENTA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTADORVISITAS
    {
        public int ContadorVisitasId { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> FechaVisita { get; set; }
    }
}
