//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_SONOLIENTA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTENOS
    {
        public int ContactenosId { get; set; }
        public string NombreSolicitate { get; set; }
        public string TelefonoSolicitante { get; set; }
        public string EmailSolicitante { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
    }
}
