//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_SONOLIENTA
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int UsuarioId { get; set; }
        public string NombreCompleto { get; set; }
        public string UsuarioRed { get; set; }
        public string Clave { get; set; }
        public string Telefono { get; set; }
        public Nullable<byte> Estado { get; set; }
    }
}
